### ISSUE TITLE
Shaders unable to find/open blending shader

### ISSUE THREAD

**Issue by Azurarara** [Radegast-FFXIV/reshade-shaders#10]
For some reason it seems like the shaders when being compiled cannot find the blending shader nor the reshade shader despite them being in the folders with the include files
![Screenshot (8)](https://github.com/Radegast-FFXIV/Warp-FX/assets/147489054/b68ce7a6-4fb1-4308-a3cc-d542d30cd752)
![Screenshot (6)](https://github.com/Radegast-FFXIV/Warp-FX/assets/147489054/786c82df-42d2-4ae4-8551-2a87352af12d)
I'm unsure as to how to fix it

**Comment by Radegast-FFXIV** [comment]
No worries at all. You'll want to clear out any of the files you've added to the `reshade-shaders/Shaders` folder that you added there to avoid having the broken Warp-FX shaders appearing alongside the fixed ones. This also includes removing the `Include` folder. ***Don't remove Blending.fxh and ReShade.fxh.*** Once you remove the added files, follow the instructions below to get yourself set up.

1. After you download and open the zip folder, you'll see something similar to the screenshot below.
![Screenshot 2023-10-10 014602](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/f7c2a857-4d37-47e4-9668-ec5b0e883f0b)

2. Create a folder in your `reshade-shaders/Shaders` folder titled `Warp-FX` and copy the contents of the ZIP file into the newly created `Warp-FX` folder. 
![Screenshot 2023-10-10 014651](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/241627ae-8aef-4d5b-9039-4b0100dc34ba)

3.The contents of the Warp-FX folder should be the following.
![Screenshot 2023-10-10 014707](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/a0ca849a-7e7a-44ce-80d8-4676b8465289)

4. In the settings tab, press the "+" button under the `.\reshade-shaders\Shaders` path where it says "Effect Search Paths" (make sure it's not the one that says "Texture Search Paths"), click on the "+" button, and navigate into `reshade-shaders\Shaders\Warp-FX` and click the `Select` button to add it to the effect path list. 
![Screenshot 2023-10-10 015748](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/7e207317-40cc-471d-b39d-015dcecf6d1f)
![Screenshot 2023-10-10 015955](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/06347465-6946-4de6-89dc-9256bb9c6de5)

5. Finally, hit the `Reload` button and they should  work.
![Screenshot 2023-10-10 020048](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/f8f4098b-9c74-4c73-ae5e-799d708e054f)



I realize that my installation instructions in the "Releases" aren't the most clear, so I'll update the README to include proper instructions for posterity. Sorry you had to go through this. Let me know if you need any further clarification.
