### ISSUE TITLE
Buffer option errors

### ISSUE THREAD

**Issue by Radegast-FFXIV** [Radegast-FFXIV/reshade-shaders#12]
![Screenshot 2024-01-28 175112](https://github.com/Radegast-FFXIV/Warp-FX/assets/157980730/5408b542-1448-4928-b9e0-a883c8f8d159)

Hey, I followed this issue to fix similar errors, but it landed me down to this now occurring.

_Originally posted by @Illyrielle in https://github.com/Radegast-FFXIV/Warp-FX/issues/9#issuecomment-1913659543_

**Comment by Radegast-FFXIV** [comment]
@Illyrielle This is an issue on newer reshade versions where these values are not used anymore. Please re-download the problem shaders either from the release tab or from the source directly and replace their respective files in the reshade-shaders folder. Please let me know if his works.

**Comment by Illyrielle** [comment]
> @Illyrielle This is an issue on newer reshade versions where these values are not used anymore. Please re-download the problem shaders either from the release tab or from the source directly and replace their respective files in the reshade-shaders folder. Please let me know if his works.

I did just that, and even if I had already done it on a clean install of ReShade once yesterday, apparently doing it one more time worked. I am clueless what was different this time, but glad it's in order now.

**Comment by Radegast-FFXIV** [comment]
Updating ReShade doesn't necessarily update the shaders themselves if they've been downloaded/moved over. I'm glad it's working for you now.
