### ISSUE TITLE
SpliceRadials.fx not compiling in ReShade 6.1.0

### ISSUE THREAD

**Issue by Xaiamas** [Radegast-FFXIV/reshade-shaders#13]
Everything is set up according to the readme, but this fx file fails to compile.
Error X3004: undeclared identifier 'x_coord'

**Comment by Radegast-FFXIV** [comment]
Sorry for the long delay on the responses. I'll take a look at it tonight.

**Comment by Radegast-FFXIV** [comment]
I have re-checked using the latest release and couldn't reproduce the issue. Please confirm that you've downloaded the latest files via the latest release ZIP on the Releases page or updated your shaders through the ReShade executable. Additionally, please make sure the installed shaders follow this convention (using Witch Spring R as an example game):

![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/5325b906-329f-4dd2-a2d3-7301ec70a054)

![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/c874a9d8-0642-45c0-9d91-d21991af8020)

![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/b8759e58-8186-4e57-b9aa-6b7ad9c783d8)

The "Effect search paths" field in the Settings tab should look like this.
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/939e26e5-610c-4439-9739-473f0f9693d3)

Here's proof that it works.
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/a4744da5-f20a-4a94-8432-d3cfe6d9a8e3)

**Comment by Xaiamas** [comment]
My setup matches what you show.

![Screenshot 2024-04-11 084722](https://github.com/Radegast-FFXIV/Warp-FX/assets/17252491/a89142f7-d2f2-49d8-9fe4-fd1934a954b8)

![Screenshot 2024-04-11 084608](https://github.com/Radegast-FFXIV/Warp-FX/assets/17252491/2c5919fa-9724-4986-b243-2434a31d8591)

Proof of it not working:

![Screenshot 2024-04-11 085044](https://github.com/Radegast-FFXIV/Warp-FX/assets/17252491/14470995-401a-4e30-a005-83ebc3a5e4cd)

**Comment by Radegast-FFXIV** [comment]
@DarknessChild A couple requests: 

- Can you check the contests of Include/RadegastShaders.Positional.fxh and confirm that you have a variable called 'x_coord' there? If not, that might be the file you need to replace. It should look like this:
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/9cc43896-6488-4131-8855-90fca4b109dc)
- Can you post a screenshot of the Logs tab with the error? This will help me figure out exactly what's going on.

**Comment by Xaiamas** [comment]
The file contains the expected parameter:
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/17252491/deee2308-6f75-4885-92ca-12a4eee5a5b1)

Here's the log for reshade:

![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/17252491/777f9974-2ea8-46f8-b513-d5a011e0c63e)

**Comment by Radegast-FFXIV** [comment]
Thanks for the quick responses. How strange... Next thing to confirm is that the `#include` chain isn't broken from the `SplicedRadials.fx` file all the way to the `RadegastShaders.Positional.fxh` file.

- At the top of `SplicedRadials.fx`, we should see these includes:
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/89581561-7602-492b-bb82-6d38b9a25f08)
- At the top of `Spliced Radials.fxh`, we should just see `Swirl.fxh`:
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/ebc1772b-d658-477f-9052-2e3a1fec8ae0)
- At the top of `Swirl.fxh`, we should see a rather large `#include` block with `RadegastShaders.Positional.fxh` as one of those includes:
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/58457062/03833b8f-fa4e-438c-9c38-42df48801131)

**Comment by Xaiamas** [comment]
Yes, the includes chain does seem unbroken. I was following that as you replied.
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/17252491/cac1125b-30d6-49f9-9846-b4d9f9f3e881)
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/17252491/d1462aac-44ae-44d1-824f-6bfdd3f53cc7)
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/17252491/6da4de70-1363-49cf-ae78-786b7a5763c0)

**Comment by Radegast-FFXIV** [comment]
One thing that I have a hunch about (though I'm not sure how it would factor into this problem at all) and I really should change is the `#include "../ReShade.fxh"` line. Could you change that to just `#include "ReShade.fxh"` and reload the shaders? It really shouldn't fix anything, but it'd be silly to leave it up to that.

**Comment by Xaiamas** [comment]
No, unfortunately, it's never that simple. Made the Update to the include statment, and reloaded the shaders in reshade. the error remains the same.

**Comment by Xaiamas** [comment]
Nope, it was even simpler. I was using my shaders folder from my old Gshade install. it had your fx in the root. I failed to remove those/ the includes file from the root of the shaders folder. removing those meant that it now loads the ones from the WarpFX directory. this has solved the issue.

**Comment by Radegast-FFXIV** [comment]
Good to hear.

**Comment by Evilmcgee** [comment]
I know I'm kind of necroing this thread, but I think I'm having the same problem, with probably the same solution, but I don't know how to enact said solution, would it be possible for you to explain it to me like I'm dumb? xD

**Comment by Radegast-FFXIV** [comment]
@Evilmcgee Actually, I received word that there's some breakage with SlitScan and RadialSlitScan in the newest ReShade release, so I'll be fixing that tonight.

**Comment by Evilmcgee** [comment]
Oh awesome! Thank you!
