### ISSUE TITLE
Does not compile.

### ISSUE THREAD

**Issue by TheBitcoinBaron** [Radegast-FFXIV/reshade-shaders#7]
Doesnt compile, the log says it **can't open** the FXH files despite me putting them where it is looking for them.

**Comment by TheBitcoinBaron** [comment]
![image](https://user-images.githubusercontent.com/27411279/167893341-0f515965-ece8-4635-9260-70c44aec5056.png)

**Comment by TheBitcoinBaron** [comment]
The FXH files giving the error were not in the download. It is looking for FXH files not included with the zip download.

**Comment by TheBitcoinBaron** [comment]
after downloading the luluco shaders which are the files which were missing from this download.... the following error: 
![image](https://user-images.githubusercontent.com/27411279/167897215-ce25370d-5fd3-438e-b349-b47bab6052ff.png)

**Comment by Radegast-FFXIV** [comment]
@TheBitcoinBaron This is something I should've gotten to earlier. You will need to download the Blending.fxh file found [here](https://github.com/crosire/reshade-shaders/blob/slim/Shaders/Blending.fxh) in crosire's reshade-shaders repo. This file will need to be added to the same location where you are unloading my shaders. This file is normally automatically downloaded when deploying ReShade. 

I've included a Prerequisites section to my README to help others out. Thanks for pointing this out.
