### ISSUE TITLE
They don't load correctly

### ISSUE THREAD

**Issue by orrinpants** [Radegast-FFXIV/reshade-shaders#8]
They have errors

**Comment by orrinpants** [comment]
Maybe it's outdated.

**Comment by Radegast-FFXIV** [comment]
@orrinpants

**Comment by Radegast-FFXIV** [comment]
Could you post the logs, if possible?

**Comment by orrinpants** [comment]
I didn't mean it crashed or anything, the shaders just don't load correctly

**Comment by Radegast-FFXIV** [comment]
That's understandable. What I'm looking for are the logs in the log tab that ReShade shows. I'll need you to do the following:

1. Load whatever game you're having issues with. 
2. When ReShade loads, open ReShade and click on the Logs tab.
3. Scroll down to any lines in red involving my shaders and take some screenshots.
4. Post them here.

**Comment by Radegast-FFXIV** [comment]
I went ahead and pushed a new release if you've been using the Release version. Please give those a try.
