### ISSUE TITLE
Error on almost every single plugin

### ISSUE THREAD

**Issue by ZezaReignhalt** [Radegast-FFXIV/reshade-shaders#9]
So moving from Gshade to reshade and these started throwing an error on Reshade.  almost all of em throw an identifer error and a render_type error.

I redownloaded them just to be safe but that does not fix the issue.

Attached are the screens.

![2023-02-06 22_08_38-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146527-9c7b9c67-beb1-4631-9da9-f4fce48c7e00.png)
![2023-02-06 22_08_48-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146529-a07df65f-ba9c-4427-9cdb-22818c3c11c7.png)
![2023-02-06 22_08_55-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146530-63724854-77f4-412f-b642-e2712f9f3c7e.png)
![2023-02-06 22_09_20-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146532-ea8143ba-6320-441f-87f6-e274e6d77e35.png)
![2023-02-06 22_09_43-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146535-128850f1-9735-49bb-8e3d-a33f4f0b472e.png)
![2023-02-06 22_11_28-FINAL FANTASY XIV_pluginlist](https://user-images.githubusercontent.com/37465716/217146538-b38418f1-529f-43f9-b54e-f40451deb47a.png)
![2023-02-06 22_07_53-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146539-d0c6eae9-8bba-4d5c-b9f3-c6cd445a1b9d.png)
![2023-02-06 22_08_09-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146541-94f0c2dc-8a2c-4c61-98fe-9cf3d2626656.png)
![2023-02-06 22_08_17-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146542-676af8bc-0e19-4bdc-a4f7-975747d72299.png)
![2023-02-06 22_08_24-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146543-9a68fae5-4b17-4aaf-87ce-ea3da76b9dcf.png)
![2023-02-06 22_08_29-FINAL FANTASY XIV](https://user-images.githubusercontent.com/37465716/217146544-593b9b7c-32cb-4ef0-be66-1ae22cba0722.png)

**Comment by Radegast-FFXIV** [comment]
Judging by the issue with the semicolon, the shader files appear to be dated. Try grabbing the files from the zip [here](https://github.com/Radegast-FFXIV/Warp-FX/archive/refs/tags/v1.3.2.zip). 

1. Go to your "reshade-shaders/Shaders" directory.
2. Download the zip file mentioned above. There should be a "Shaders" folder within the zip file. Extract the *contents* of that "Shaders" folder (including the "Include" folder) into the "reshade-shaders/Shader" subfolder.
3. In your game, open your ReShade menu (default will be the Home key, but can be changed).
4. Go to the "Settings" tab and confirm you have an entry for `.\reshade-shaders\Shaders` in your Effect search paths list. The search list does not have to be as long as the one I'm using, but those directories are where ReShade will look for shader files.
5. Click the "Reload" button at the bottom of the "Home" tab.
6. Report any issues if they are still occuring.
7. If no issues appear in the log, attempt to activate any one of the shaders you were having issues with by using the search bar to search of the effects that were broken. Activate/deactivate one at a time to confirm they work. Report any issues that arise.

Here are some images to help you.
![image](https://user-images.githubusercontent.com/58457062/217211838-14129263-d823-4119-a2a1-04f5ba2ed820.png)

![image](https://user-images.githubusercontent.com/58457062/217215727-5d2d5627-5672-4743-8c5a-1269857a3d91.png)

![image](https://user-images.githubusercontent.com/58457062/217214483-df1ad06b-b006-4978-a194-f9e55f880537.png)


Please let me know if everything works as intended.

**Comment by ZezaReignhalt** [comment]
The semicolon error went away but now i am left primarily with identifier error and render type errors.   The errors i posted yesterday were from the current 1.3.2 folder.  I redownloaded via the link you provided however they are still not compiling.
![Error](https://user-images.githubusercontent.com/37465716/217288983-bc368d63-7e0e-4293-a768-977bcb7fd5d9.png)
![folder1](https://user-images.githubusercontent.com/37465716/217288985-e6bdacc8-8282-4f28-98a9-c546a13ee4fd.png)
![folder2](https://user-images.githubusercontent.com/37465716/217288986-86bf2c9c-d180-4902-b9ba-fe33d0654135.png)
![Current path](https://user-images.githubusercontent.com/37465716/217288989-2622ce5c-08c8-4365-acdd-bb8dc96a34ea.png)

**Comment by ZezaReignhalt** [comment]
its the same error for the following ones
![errorcompiling](https://user-images.githubusercontent.com/37465716/217289325-0173451b-052b-42fa-ac37-c6ea4766cb17.png)

**Comment by Radegast-FFXIV** [comment]
Thanks. One more question. Do you have a BlendingModes.fxh in the reshade-shaders/Shaders directory?

**Comment by ZezaReignhalt** [comment]
I'll have that to you by this afternoon with an answer

**Comment by ZezaReignhalt** [comment]
Does not appear that I have a BlendingModes.fxh in this directory or any of my previous Gshade backups prior to moving to reshade.

**Comment by Radegast-FFXIV** [comment]
Apologies. `Blending.fxh` is the file you need to look for.  Please copy that into the "Include" folder. If you don't have that file,  you may extract it from the zip file [here](https://github.com/Radegast-FFXIV/Warp-FX/files/10678884/Blending.zip) and place it into both your Shaders folder and the Shaders/Include folder seen below.


![image](https://user-images.githubusercontent.com/58457062/217350461-91cd410a-278f-466e-bee5-c86f3c43ede9.png)

![image](https://user-images.githubusercontent.com/58457062/217350592-1d7292c2-9854-466e-b236-d3ceb9366680.png)

Let me know if issues persist.

**Comment by ZezaReignhalt** [comment]
I will test that this afternoon and followup.

**Comment by ZezaReignhalt** [comment]
it was missing from the include folder.  after adding it to the include folder it now compiles.  I appreciate the assistance.

it was in the regular shaders folder only, not the include folder for some reason.

**Comment by Radegast-FFXIV** [comment]
The `Blending.fxh` file is usually located at the root folder (Reshade/Shaders). Reopening this as I will update these files to make sure they point to the `Blending.fxh` at the root folder without the need to copy-paste the file into the Includes.

Thanks again for helping me figure this out as a few people have already had this issue as well.

**Comment by ZezaReignhalt** [comment]
Glad to help

**Comment by SGBGames** [comment]
I seem to be still having this same issues after following up with this thread  well at least a few of them it seems
![image](https://github.com/Radegast-FFXIV/Warp-FX/assets/103670347/33bd3a78-fd35-4515-a797-29cbf3058eed)

**Comment by Radegast-FFXIV** [comment]
Hi there. I'll take a look at my shaders today and update the necessary imports.

**Comment by Radegast-FFXIV** [comment]
@SGBGames I've went ahead and updated my shaders. Please redownload them by either downloading the contents of the release zip or by rerunning your ReShade installer and selecting "Modify" to re-download the shaders.

**Comment by Illyrielle** [comment]
![Screenshot 2024-01-28 175112](https://github.com/Radegast-FFXIV/Warp-FX/assets/157980730/5408b542-1448-4928-b9e0-a883c8f8d159)

Hey, I followed this issue to fix similar errors, but it landed me down to this now occurring.

**Comment by Radegast-FFXIV** [comment]
@Illyrielle This should be a separate issue as it's not quite the same. I'll make one for this.
